# Generated by Django 5.1 on 2026-05-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_farmstory_productreview_recipe_product_is_surplus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens_declared',
            field=models.BooleanField(default=False, help_text='Tick to confirm allergen information has been reviewed and is complete for this product.'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='producer_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='producer_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
